apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: git-repo-composition
spec:
  compositeTypeRef:
    apiVersion: api.cloudgenie.org/v1alpha1
    kind: XGitRepo
  mode: Pipeline
  pipeline:
    - step: create-repository
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: repo
            base:
              kind: Repository
              apiVersion: repo.github.upbound.io/v1alpha1
              spec:
                providerConfigRef:
                  name: gitub-provider-config
                forProvider:
                  description: "A repository managed by Crossplane"
                  visibility: public
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.name
                  strategy: string
                  string:
                    fmt: "%s-repo"
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.name
                toFieldPath: spec.forProvider.name
          - name: deployment-file
            base:
              kind: RepositoryFile
              apiVersion: repo.github.upbound.io/v1alpha1
              spec:
                providerConfigRef:
                  name: gitub-provider-config
                forProvider:
                  commitMessage: "Add deployment setup file"
                  file: deployment.yaml
                  content: |
                    apiVersion: apps/v1
                    kind: Deployment
                    spec:
                      replicas: 2
                      template:
                        spec:
                          containers:
                            - name: app
                              ports:
                                - containerPort: 80
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.name
                  strategy: string
                  string:
                    fmt: "%s-repo-deployment-file"
                toFieldPath: metadata.name
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.name
                  strategy: string
                  string:
                    fmt: "%s-repo"
                toFieldPath: spec.forProvider.repositoryRef.name
