kind: Secret
apiVersion: v1
metadata:
  name: github-provider-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials.json: ewogICJ0b2tlbiI6ICJnaHBfZEV6SjlJdFJ3TGVHa3p0YlVqZmQ2T1V4bjlGNGoxMDNqbkxaIgp9Cg==
