apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-genie-resources
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - path: resources/git-repo
      repoURL: "https://github.com/deepakvbansode/idp-cloudgenie-state.git"
      targetRevision: HEAD
    - path: resources/golang-app
      repoURL: "https://github.com/deepakvbansode/idp-cloudgenie-state.git"
      targetRevision: HEAD
    - path: resources/react-app
      repoURL: "https://github.com/deepakvbansode/idp-cloudgenie-state.git"
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
